# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=8000)),
                ('minutes', models.IntegerField()),
                ('entry_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todolist_item', to='secu.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('minutes', models.IntegerField()),
                ('entry_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todolist_itemstep', to='secu.User')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.Item')),
                ('person_in_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secu.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('work', models.CharField(max_length=8000)),
                ('minutes', models.IntegerField()),
                ('entry_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todolist_itemwork', to='secu.User')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.Item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('order', models.IntegerField()),
                ('entry_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todolist_status', to='secu.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('order', models.IntegerField()),
                ('entry_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todolist_step', to='secu.User')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todolist.Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StepStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('entry_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todolist_stepstatus', to='secu.User')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.Status')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.Step')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='itemstep',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.Step'),
        ),
        migrations.AddField(
            model_name='item',
            name='step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todolist.Step'),
        ),
    ]
