# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepstatus',
            name='entry_user',
        ),
        migrations.RemoveField(
            model_name='stepstatus',
            name='status',
        ),
        migrations.RemoveField(
            model_name='stepstatus',
            name='step',
        ),
        migrations.DeleteModel(
            name='StepStatus',
        ),
    ]
