# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Right',
            fields=[
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('detail', models.CharField(max_length=8000)),
                ('view_name', models.CharField(max_length=200)),
                ('pattern', models.CharField(max_length=200)),
                ('selector', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('detail', models.CharField(max_length=8000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoleRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=50)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('entry_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_user_self', to='secu.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('entry_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secu_userrole', to='secu.User')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secu.Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secu.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='roleright',
            name='entry_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secu_roleright', to='secu.User'),
        ),
        migrations.AddField(
            model_name='roleright',
            name='right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secu.Right'),
        ),
        migrations.AddField(
            model_name='roleright',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secu.Role'),
        ),
        migrations.AddField(
            model_name='role',
            name='entry_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secu_role', to='secu.User'),
        ),
        migrations.AddField(
            model_name='role',
            name='rights',
            field=models.ManyToManyField(through='secu.RoleRight', to='secu.Right'),
        ),
        migrations.AddField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(through='secu.UserRole', to='secu.User'),
        ),
        migrations.AddField(
            model_name='right',
            name='entry_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secu_right', to='secu.User'),
        ),
    ]
